perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppsView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/ValidatedEmail.java

WUI: In order to display most of user applications, always search by session info.
- Must be deployed after update to the perun-registrar component.
WUI: Prevent null pointer in case email is not pre-filled from federation
- Check on validated mail form item was stopped by NullPointerException
when no value was pre-filled from IdP or Perun. Now we assume, that
"custom" is not selected since it has no effect (select is not visible).

WUI: Fixes to registrar component

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/UserExtSource.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/IdentitiesView.java

make remove button disabled if UserExtSource is marked as peristent.
Should be deployed after pullrequest to Perun core will be deployed. 
https://github.com/CESNET/perun/pull/1215

PROFILE: Consume new persistent flag from UserExtSource in Perun.

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.java

Profile app use brand.profile.title.[lang] property to fill title. If not configured "User profile" is used.

PROFILE: Read app title from config file.

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java

- To prevent user from multiple submission of same application,
RPC throws AlreadyProcessingException when same application is
being processed. GUI must silently skip it to wait for original
request to finish.
Merge only after: https://github.com/CESNET/perun/pull/1639
is deployed to production.

WUI: Silently skip all actions if AlreadyProcessingException is thrown

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/AttributeDefinition.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.ui.xml
perun-wui-profile/src/main/resources/common/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation_cs.properties

* Now you can customize what attributes are shown in
personal page by setting theirs urns in config file.
* Example: profile.personal.showAttributes=special:user:fullName,
urn:perun:user:attribute-def:def:organization,
urn:perun:user:attribute-def:def:preferredLanguage,
urn:perun:user:attribute-def:def:preferredMail,
urn:perun:user:attribute-def:def:timezone,
urn:perun:user:attribute-def:def:preferredShells

Customize attributes on Profile personal page

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java

* Links were not displayed properly when they were not at the beginning
of the description text.
* Fixed attribute description when there was only the english
value with displayed ']'
* Removed some debug logs

Fix links on Profile personal page

---

perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/widgets/Wayf.java

- Even on /fed/ authz user might have offered certificate and since
on deb9 we can't request cert again once connection is established,
we must always change the hostname to go to (if possible).

WUI: Always try to change hostname when joining certificate

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/beans/Locale.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/beans/PersonalAttribute.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java

* Now it is possible to define for each attribute name that will be
displayed in config file.
* Now the syntax for defining attribute that should be displayed looks
like this:
[EnName|CzName]urn[EnDescription|CzDescription]
* The only required parameter is the urn.
* If there is only one name or language specified, it will be used as a
en version. In other words, you can not define only Czech version. You
can define EN and CZ or EN or none.
* Created enum Locale to represent current page local.

Profile - Personal attributes name custom configuration

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/model/RegistrarObject.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/FormStep.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/FormStepManager.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/GroupInitStep.java

- When anonymous person submits vo registration with automatic
approval, user is created in Perun. When he continues with
registration to group, this information is not reflected on the form,
since it was loaded before.
- Now we reload group form during the process, hence form items can be
pre-filled with data from Perun (submitted vo form) and group form
is submitted with user id set.
- Fixed displaying vo logo.
- Added methods to set back form and exception into registrar object.

WUI: Refresh group initial form

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItem.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemEditable.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/PerunFormItemValidatorImpl.java

- If form item doesn't have properties for specific locale, it showed
wrong form (fallback to labels, empty help or error messages).
- Now for cases when localized property is null or empty we fallback
to "en" lang and return it instead.
- If its still null or empty, we fallback to previous solutions.
- This helps instances with a single language, since if user accessed
them with locale supported by our GUI, it draw wrong form.
Now it falls back to English.

WUI: Fallback to english on registration form

---

perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/pages/JoinPage.java
perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/pages/SelectPage.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/AttributesManager.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/model/beans/RichUserExtSource.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/identities/IdentitiesPresenter.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/identities/IdentitiesUiHandlers.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/identities/IdentitiesView.java

- When identity is from foreign proxy (has ues authenticating-authority
attribute), we fallback to displaying its value as entityId
to be translated on user profile and consolidator.
Same goes for login/actor property, where we fallback to eppn
attribute.

WUI: Show entityId and eppn from UES attributes for foreign proxies

---

.editorconfig
.gitignore

* Now the defined TAB size is 4 and GitHub should respect this settings.

Changed TAB size

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java

- We offered VO extension after initial group application was submitted.
Since we now support group extension too, we must cover the case, when
group extension is empty (extension is disabled for such group).
In such case user ends up with an empty message without ability to
continue. Hence we offer VO extension before group extension form.

WUI: Offer VO extension before empty group form

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/GeneralObject.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolverImpl.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java
perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties

- Add newline to error/warning texts displayed on registration
form (including translation).
- Make "continue >" button more visible by using SUCCESS and
LARGE button style.
- Removed unused code from GeneralObject.

WUI: Better ux for continue button and error messages

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItem.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Password.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/UsernameValidator.java

- Relation to perun attribute used to prefill and store form item
value was split to source and destination attributes.

WUI: Registrar form items now have split src/dst perun attribute

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItemData.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java

- Pre-filled value in USERNAME type of application form can be marked
as generated. It is then considered as editable and on form submission
pre-filled value is cleared to make sure, new login is registered and
not considered as "already existing".

WUI: Handle generated logins

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java

- When user visits registration form again and his application is pending,
then dialog for joining identities was displayed and stuck the user for 5s,
just to later display the fact, that application is pending.
- Now we display notice about pending application from start.

WUI: Do not offer similar users dialog when user have pending applications

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/PerunException.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItemData.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolver.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolverImpl.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryImpl.java
perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties

- These are not conflicting changes, which are part of "registrarWorkflow"
branch, which will be finished later. Purpose is to ease deployment
of server side changes.
- DuplicateRegistrationAttemptException now contains whole Application
object including ApplicationFormItemData.
- We can compare loa of application form item data as integer,
and this fixes issue with loa < 1.
- Adds new translation for future use.
- Since we rename DuplicateRegistrationAttemptException as a hack,
we must check renamed "DuplicateExtensionAttemptException" when resolving,
whether user applied for vo/group extension.

WUI: Updates to translation, loa and duplicateRegistrationAttemptException

---

perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/settings/sshkeys/SshKeysView.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/settings/sshkeys/SshKeysView.ui.xml

* If the attribute for admin ssh keys does not exist in Perun, the table
with admin ssh keys is hidden.

Profile - hide admin ssh keys

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java

- Message which is shown in registrar when entering login which is
already taken was edited. It was "Login <b>is not available!</b>"
and now it is "Login <b>is not available!</b> Please choose another."

Changed default message for loginNotAvailable

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java

- When redirecting back to the service (or another registration)
we must wait, so that LDAP is updated with new user and group
membership data. Then we can redirect.

WUI: Introduce timeout when summary step is skipped

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java

* When the user is already a member of a vo or a group, the previous
result is null and the application cannot be loaded. In this case, we
just want to skip the check of the application state.
* This old implementation caused errors for users who were already
members with the combination of targetExisting query parameter.

Registrar - fix of null

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalPresenter.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalUiHandlers.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.ui.xml
perun-wui-profile/src/main/resources/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation_cs.properties

- Send request to change preferred mail with /profile/
path, so that mail verification is done on profile again.
- Support mail verification on profile/personal page.

PROFILE: Support preferred email change on profile

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java

- Finding of similar users while submitting the registration was made
optional. Now it will be not trigered when the property
registrar.findSimilarUsers.disabled is set to true.

Optional similar users finding

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/FormStep.java

* When users failed to submit the application for the first time, the
registrar allowed them to try again. But if they succeeded, they were
not redirected to the summary page and it seemed that the submission
failed again.
* Fixed by changing exception in the submission result to null, if the
submission was successful. This is used later on to check the result of
the submission.

Registrar - redirect users to summary page bug fix

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/RegistrarManager.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItem.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolverImpl.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailPresenter.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.ui.xml
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppsPresenter.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppsView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppsView.ui.xml
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Checkbox.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Combobox.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/FromFederation.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Password.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItem.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemEditable.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemStatic.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Radiobox.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Selectionbox.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextArea.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextField.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Timezone.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Username.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/ValidatedEmail.java
perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties

- We want users to be able to edit submitted applications.
- Added new api callback for it.
- PerunForm can now have 3 states, PREFILLED (initial on
submission), EDIT (editing submitted) and PREVIEW.
Each form item respect these states individually. Some
form items are not editable/updatable (eg. login,
non-editable fields).
Also form items data of deleted template form item are
not editable.
- Reworked, how we construct form item data before submission.
- Do not display mail verification notice on applications not
related to mail to be verified.

REGISTRAR: Allow editing submitted form to users

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/JsUtils.java

- Pre-pend '0' if day or month is < 10.

Fixed format of current date string in JsUtils

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItem.java
perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItemData.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunForm.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Checkbox.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Combobox.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItem.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemEditable.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextField.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Username.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/ValidatedEmail.java

* Application form items have new properties - hidden, disabled and
updateable. The registrar GUI will now support these properties.
* Updatable - on the submitted application detail, it is now possible to
update only items, which are stated as updatable. There are some
exceptions, some types can never be updatable e.g. USERNAME.
* Hidden - items will be now hidden depending on their `hidden` value.
`ALWAYS` - item will never be displayed. `NEVER` - default behaviout,
item will be always visible. `IF_PREFILLED` item will be hidden, if it
is prefilled by the backend (or if `hidden_dependency` is specified, it
will be checked instead).
* Disabled - similar behaviour to the `hidden` property - the item will
be disabled depending on the specified condition.

Registrar - items rework

---

pom.xml

- During update to JDK 16 we updated also GWT compiler
java version to 11. While its OK for compiling the app to
production, we can't run app locally in development mode
like that, since embedded Jetty server (9.2) doesn't support
classes compiled with Java 11.
- Possible solution for update to Java 11 is part of
pull-request #141, but its still WIP.

Push back to Java 8 for GWT

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Username.java

* There was a problem with the `enabled` property of the `Username`
object. The value of this property was set to true, when instance of
this class was created. This property was used in the `initWidget` method.
The `initWidget` method was called from a constructor of a super class
and that was a problem. When the super constructor was called, variables
declared in the `Username` class were not initalized. Therefore, the
`enabled` property had the default value - false.
* This caused the username to be always disabled.
* I discovered that the property was not actually needed, co the fix is
just to remove it.

BugFix - username filed was always disabled

---

perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java
perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.ui.xml
perun-wui-profile/src/main/resources/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation_cs.properties

* Preferred mail is changed after redirecting to the profile, query parameters are cleared
* If the request isn't valid anymore or doesn't exist, modal with info is displayed

Added handling for invalid pref mail requests

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextArea.java

- We formerly limited size of user input in TextArea form items to 3999,
because we were limited by Oracle DB. Now we use postgres, which can
take up to 1GB. We don't want users to upload so much, but
limit was increased to 10 000 chars.

Increase size limit for TextArea form items

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/GroupInitStep.java

* When moving to group application from vo application we want to reload group application form
every time, because user might have filled-in data to vo application that we want to prefill to
group application. Till now both forms were loaded beforehand and vo application data would not be
used.

 feat(registrar): reload data when moving to group application form

---

.releaserc.json
pom.xml

- Module perun-wui-admin was removed from build and release because it
is not used.

remove perun-wui-admin from build and release

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextArea.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextField.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/SshKeysTextAreaValidator.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/SshKeysTextFieldValidator.java
perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties

- In case of using TextArea widget for managing SSH keys we now
perform more verbose checks for their format.
- Decision in validator is made based on destination attribute
"user:def:sshPublicKey".
- Multiple keys are expected to separated by comma (default when
pre-filled) or by newlines.
- Added specific translated error states for SSH keys.

feat(registrar): support better SSH keys input validation

---

perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/client/resources/PerunPwdResetTranslation.java
perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.ui.xml
perun-wui-pwdreset/src/main/resources/cz/metacentrum/perun/wui/pwdreset/client/resources/PerunPwdResetTranslation_cs.properties

- Check if account has been activated and prevent repetitive activation.
- Display custom texts when its activation and einfra namespace for
both success and error messages.
- Custom messages are active only for /it4i/ prefix, since they mention
account migration/import.

feat(pwd-reset): display custom messages for einfra

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/AlertErrorReporter.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolverImpl.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties

- Show better info when request is aborted by the browser in registrar.
- Hide submit button in AlertErrorReporter as we can't fix it.
- Fixed line endings in AlertErrorReporter.

fix(registrar): better info for users when return code 0 happens

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Selectionbox.java

- Previously generic "--- Not selected ---" option in the select box returned
"null" string value.
- Now we return empty string which is correctly recognized as an empty/null
value for the attribute on Perun side.
- This prevents bug when such value should be stored in attribute
with checked syntax.

fix(registrar): return empty value if no option selected in selectbox

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Selectionbox.java

* Selection box on preview now displays user friendly labels instead of pure values.
* Selection box in the edit mode is now disabled if the item is not updatable.

fix(registrar): selection box preview and edit mode

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java

* uppercase characters should be allowed in email domain - some IdPs send them that way

fix(registrar): allow uppercase in application mail domain

---

.releaserc.json

* release is otherwise not triggered when commit containing breaking change marked with exclamation mark is merged

ci: use conventional commits preset for release

---

perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/widgets/Wayf.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java

Missing AuthenticationContextClassRef Caused some IdPs to fail. They do not understand the `unspecified` value, nor do they understand the IdP Hint, if it somehow got forwarded (e.g. LS AAI case). With this tweak, even if it gets forwarded, IdP can respond with
`urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport` and will not fail.

fix: 🐛 Add `PasswordProtectedTransport` to IdP hint ACRs

---

perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/OwnerColumnProvider.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java

- It is unnecessary to load member for user if the user is not present in session (id = -1).
- Handle it the same way as when user is not member.
- Removed unused import.

fix: don't try to load member when there is no user

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/GroupCheckBox.java

* Use the group names in embedded group form item (for group) without prefix.
* This change is applied only for group forms.

fix(registrar): use shorter names of ebmedded groups withou prefix

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/CheckboxValidator.java
perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties

Provide more meaningful default error messages for inputs that do not have format, e.g. radio, checkbox, select, embedded_gr_app.

fix: 🐛 Different default error msg for inputs like radio, check

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java

Fixed version redirect user back to the service after the modal window is closed. Previous implementation caused users to be stuck on opening the modal window informing them that the application is not processed and the service might redirect them back to this reg. form. However, this causes problems if users are redirected somewhere else, e.g. homepage of the service.

fix: 🐛 Redirect user back to service after modal closes

---

perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/GroupCheckBox.java

- Override text on checkboxes for embedded group applications only if resulting value is not empty.
- Behavior depends on the presence of group param in URL query and its value.

fix: override checkbox text only if not empty
