CESNET/perun-wui

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ExtSource.java
- Added new types of ExtSource.
> WUI-CORE: We no longer get attributes within ExtSource object

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/LeftMenuView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/LeftMenuView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWui.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/FacilitiesManagementPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/FacilitiesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/FacilitiesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/VosManagementView.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PlaceTokens.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/FacilityColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/PerunDataGrid.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/PerunLoader.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/boxes/ExtendedSuggestBox.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/boxes/ExtendedTextArea.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/boxes/ExtendedTextBox.java
- Basic page for listing facilities with not active buttons.
- Proper implementation of SuggestBox (added ExtendedSuggestBox).
- Bind filter box to data grid.
- Added ColumnProvider for Facility and new PlaceTokens.
- Fixed PerunLoader widget including width issue in tables.
> WUI: Added facilities page

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWui.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/AttributesManagementPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/AttributesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/AttributesManagementView.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PlaceTokens.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/JsonClient.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/AttributesManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UtilsManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/VosManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/AttributeDefinition.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/AttributeColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/AttributeDefinitionColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/common/RTMessage.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/resources/PerunComparator.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/ErrorReporter.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/ErrorReporter.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/PerunLoader.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/PerunLoader.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/resources/PerunColumnType.java
- We can now report error to RT when it occur.
- Behavior is the same as in old UI.
- Added attributes management page to Perun admin section.
- Implemented ColumnProviders for attributes.
> WUI: Added support for error reporting

- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/client/ConsolidatorTranslation.java
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/client/JoinPage.java
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/client/SelectPage.java
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/widgets/Wayf.java
- perun-wui-consolidator/src/main/resources/common/cz/metacentrum/perun/wui/consolidator/client/ConsolidatorTranslation_cs.properties
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java
- Fixed linking to social identities on proxy IdP.
- Added "at" when displaying user identities.
> WUI: Updated identity consolidator webapp

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWui.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/UsersManagementPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/UsersManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/UsersManagementView.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PlaceTokens.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/BasicOverlayObject.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/RichUser.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/RichUserColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/resources/PerunColumnType.java
PerunAdmin - Users
UsersManager - new methods
getRichUsersWithoutVoAssigned() - for button List users without Vo
findRichUsesrsWithAttributes(String searchString, ArrayList<String> attrNames) - for button Search
new RichUserColumnProvider - default columns: Id, Name, Organization, Email, Login
new UsersManagementPresenter, UsersManagementView, UsersManagementView.ui.xml
BasicOverlayObject - new method
getListOfStrings(String name) - Return String value representation of param name as URN list.
> PerunAdmin - Users

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWui.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ServicesManagementPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ServicesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ServicesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/servicesManagement/ServiceDetailPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/servicesManagement/ServiceDetailView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/servicesManagement/ServiceDetailView.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PlaceTokens.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/ServicesManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/ServiceColumnProvider.java
new ServicesManagementPresenter, ServicesManagementView, ServicesManagementView.ui.xml for PerunAdmin - Services
new ServiceDetailPresenter, ServiceDetailView, ServiceDetailView.ui.xml for detail of service
ServicesManager - deleteService(), getServiceById(), getServices()
new ServiceColumnProvider
> PerunAdmin - Services, ServiceDetail

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWui.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ExtSourcesManagementPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ExtSourcesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ExtSourcesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/OwnersManagementPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/OwnersManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/OwnersManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/PerunManagementUiHandlers.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ownersManagement/OwnerCreatePresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ownersManagement/OwnerCreateUiHandlers.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ownersManagement/OwnerCreateView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ownersManagement/OwnerCreateView.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PlaceTokens.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/UiUtils.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/ExtSourcesManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/OwnersManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/ExtSourceColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/OwnerColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/resources/PerunColumnType.java
perunManagement - new pages Owners + OwnerCreate and ExtSources,
new Managers - OwnersManager, ExtSourcesManager
new columnProvider - ExtSourceColumnProvider, OwnerColumnProvider
new method in UiUtils - bindButtonBoxes - Bind ExtendedTextBoxes and PerunButton to work together
> PerunAdmin - Owners, ExtSource

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/TopMenu.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/RichMember.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/RichUser.java
- perun-wui-core/src/main/resources/common/cz/metacentrum/perun/wui/client/resources/PerunWui.gss
- Also use instance/default logo in app.
> WUI: Fixes for css and user/member logins display

- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/client/JoinPage.java
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/client/SelectPage.java
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/widgets/Wayf.java
- perun-wui-consolidator/src/main/resources/common/cz/metacentrum/perun/wui/consolidator/client/ConsolidatorTranslation_cs.properties
- perun-wui-consolidator/src/main/webapp/PerunConsolidator.html
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/User.java
- Kerberos realms are now translated to organizations.
- Added new IdP organizations, support for Elixir Europe.
- Fixed translation.
- Translatable Krb button (realm).
- Add coma before titleAfter part of User name.
> WUI: Support for elixir and krb translation in consolidator

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/model/ExceptionResolver.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/Summary.java
clean display exceptions in summary
fix bug in DuplicateAttemptException (typo in equals)
> REG: Double continue button resolved

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWui.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWuiPresenter.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/client/PerunWuiView.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/PerunPresenter.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/RegistrarManager.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolver.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrar.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrarPresenter.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrarView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrarView.ui.xml
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/RegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunWuiRegistrarResources.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
- perun-wui-registrar/src/main/resources/common/cz/metacentrum/perun/wui/registrar/client/RegistrarTranslation_cs.properties
- perun-wui-registrar/src/main/resources/common/cz/metacentrum/perun/wui/registrar/client/resources/css/PerunWuiRegistrar.gss
- perun-wui-userprofile/src/main/java/cz/metacentrum/perun/wui/userprofile/client/UserProfile.java
- perun-wui-userprofile/src/main/java/cz/metacentrum/perun/wui/userprofile/client/UserProfilePresenter.java
- perun-wui-userprofile/src/main/java/cz/metacentrum/perun/wui/userprofile/client/UserProfileView.java
CORE: redefine PerunPresenter as abstract
> REGISTRAR: show contact mails of VO in footer

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/AttributesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/AttributesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ExtSourcesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ExtSourcesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/FacilitiesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/FacilitiesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/OwnersManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/OwnersManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ServicesManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/ServicesManagementView.ui.xml
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/VosManagementView.java
- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/pages/perunManagement/VosManagementView.ui.xml
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/UiUtils.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/ApplicationColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/AttributeColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/AttributeDefinitionColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/ExtSourceColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/FacilityColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/OwnerColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/RichUserColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/ServiceColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/VoColumnProvider.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/PerunDataGrid.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/model/ApplicationColumnProvider.java
new filter dropdown that filters by perun columns
> filter dropdown

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/RegistrarManager.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrar.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrarPresenter.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/RegistrarPlaceTokens.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/RegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/VerifyEmailPresenter.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/VerifyEmailView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/VerifyEmailView.ui.xml
- perun-wui-registrar/src/main/resources/common/cz/metacentrum/perun/wui/registrar/client/RegistrarTranslation_cs.properties
- Implemented page for mail verification compatible with old links for registrar.
> WUI: Registrar can now verify email address from application

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/RegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
- perun-wui-registrar/src/main/resources/common/cz/metacentrum/perun/wui/registrar/client/RegistrarTranslation_cs.properties
- Use static map to speed up name translation.
- Modified translation for "federation" notice on form items.
> WUI: Updated IdP and Krb translation

- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/pages/SelectPage.ui.xml
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/widgets/Wayf.java
- perun-wui-consolidator/src/main/webapp/PerunConsolidatorElixir.html
- perun-wui-profile/src/main/webapp/PerunProfileElixir.html
- perun-wui-registrar/src/main/webapp/PerunRegistrarElixir.html
- Elixir will have own HTML pages.
- Consolidator for Elixir will use only social identities.
- Better alignment when consolidator has less than 3 groups.
> WUI: Added branding for Elixir project

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/common/FeedEntity.java
- New version of IdP feeds for Czech fed will have relative URLs.
Adding config option to specify hostname in case url is missing
http or https at start.
> WUI: Fix logo url for IdP feeds

- perun-wui-consolidator/src/main/resources/common/cz/metacentrum/perun/wui/consolidator/client/resources/css/PerunConsolidator.gss
- perun-wui-consolidator/src/main/webapp/PerunConsolidator.html
- perun-wui-consolidator/src/main/webapp/PerunConsolidatorElixir.html
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/PerunLoader.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileResources.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/OrganizationsView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/PersonalView.ui.xml
- perun-wui-profile/src/main/resources/common/cz/metacentrum/perun/wui/profile/client/resources/css/PerunProfile.gss
- perun-wui-profile/src/main/webapp/PerunProfile.html
- perun-wui-profile/src/main/webapp/PerunProfileElixir.html
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrarView.ui.xml
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarResources.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppsView.ui.xml
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/FormStepManager.java
- perun-wui-registrar/src/main/resources/common/cz/metacentrum/perun/wui/registrar/client/resources/css/PerunRegistrar.gss
- perun-wui-registrar/src/main/webapp/PerunRegistrar.html
- perun-wui-registrar/src/main/webapp/PerunRegistrarElixir.html
New pull request instead of #35
> Css corrections

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.java
Config name of URL is brand.logo.url.[lang]
> PROFILE: clickable brand logo where URL is get from gui config

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/PerunRegistrarView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
Change texts according to native speaker.
> REGISTRAR: Read app title from config file. 

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/PersonalPresenter.java
property is brand.profile.unknownUsersRedirect.en
> Profile: Redirect unknown users to configurable page

- perun-wui-admin/src/main/java/cz/metacentrum/perun/wui/admin/perun-wui-admin.gwt.xml
- perun-wui-admin/src/main/webapp/PerunAdmin.html
- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/perun-cabinet.gwt.xml
- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/perun-wui-consolidator.gwt.xml
- perun-wui-consolidator/src/main/webapp/PerunConsolidator.html
- perun-wui-consolidator/src/main/webapp/PerunConsolidatorElixir.html
- perun-wui-consolidator/src/main/webapp/PerunConsolidatorMU.html
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/perun-wui-core.gwt.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/perun-wui-profile.gwt.xml
- perun-wui-profile/src/main/webapp/PerunProfile.html
- perun-wui-profile/src/main/webapp/PerunProfileBBMRI.html
- perun-wui-profile/src/main/webapp/PerunProfileElixir.html
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/perun-wui-pwdreset.gwt.xml
- perun-wui-pwdreset/src/main/webapp/PerunPwdReset.html
- perun-wui-pwdreset/src/main/webapp/PerunPwdResetElixir.html
- perun-wui-pwdreset/src/main/webapp/PerunPwdResetMU.html
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/perun-wui-registrar.gwt.xml
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/Select.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/ValidatedEmail.java
- perun-wui-registrar/src/main/webapp/PerunRegistrar.html
- perun-wui-registrar/src/main/webapp/PerunRegistrarBBMRI.html
- perun-wui-registrar/src/main/webapp/PerunRegistrarElixir.html
- perun-wui-registrar/src/main/webapp/PerunRegistrarMU.html
- perun-wui-registrar/src/main/webapp/PerunRegistrarVSUP.html
- pom.xml
* Set GWT version to 2.8.1, GWTP to 1.6 and GwtBootstrap3 to 0.9.4
* In every *.gwt.xml file added property gssDefaultInUiBinder to true,
so the GSS is used as default.
* Added string constants in Select widget.
* Java version 1.8
> New modules and Java versions

- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/client/PerunCabinetView.ui.xml
- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/client/resources/PerunCabinetResources.java
- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/pages/NewPublicationView.ui.xml
- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/pages/PublicationsView.java
- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/pages/PublicationsView.ui.xml
- perun-wui-cabinet/src/main/resources/common/cz/metacentrum/perun/wui/cabinet/client/resources/css/PerunCabinet.gss
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileResources.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/CompleteInfoView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/GroupsView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/IdentitiesView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/OrganizationsView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/OrganizationsView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/PersonalView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/PrivacyView.ui.xml
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/ResourcesView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/ResourcesView.ui.xml
- perun-wui-profile/src/main/resources/common/cz/metacentrum/perun/wui/profile/client/resources/css/PerunProfile.gss
* Unificated basic CSS styles of applications
* Improved responsiveness of applications
> Unification of css style

- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/client/PerunCabinetView.ui.xml
- perun-wui-cabinet/src/main/java/cz/metacentrum/perun/wui/cabinet/client/resources/PerunCabinetResources.java
- perun-wui-cabinet/src/main/resources/common/cz/metacentrum/perun/wui/cabinet/client/resources/css/PerunCabinet.gss
* Now the size of the publications app will increase
more when viewed on small device.
> Publications fixed size on small devices

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/client/resources/PerunSetAffiliationTranslation.java
- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/pages/affiliation/AffiliationPresenter.java
- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/pages/affiliation/AffiliationView.java
- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/pages/affiliation/AffiliationView.ui.xml
- perun-wui-setAffiliation/src/main/resources/common/cz/metacentrum/perun/wui/setAffiliation/client/resources/PerunSetAffiliationTranslation_cs.properties
The old version did not support if a user had both roles of VO_MANAGER and GROUP_MANAGER at the same time. Now the user can choose from VOs and GROUPS that one is manager of from one select. Also if the user has only one role the select stays the same.
> WUI: setAffiliation - support for combination of GROUP and VO manager

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/groups/GroupsView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/resources/ResourcesView.java
- perun-wui-profile/src/main/resources/common/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation_cs.properties
* Fixed placeholder text where the english version contained "::"
instead of ":"
> Fixed selects placeholder text

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/JsUtils.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Application.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItem.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItemData.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Attribute.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/AttributeDefinition.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Author.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Facility.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Member.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Publication.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/RichMember.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/RichResource.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/RichUser.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Service.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/User.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/UserExtSource.java
> WUI: Implemented changes made to perun-core to wui

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/beans/PersonalAttribute.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java
* If attribute or description value contains String that starts with
'http' the anchor widget is created instead a simple Text.
> Create links on profile personal page

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.ui.xml
* Now, when the re-send email action fails, the Error Reporter is shown.
> Registrar re-send email added Alert Reporter

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java
* The descriptions of attributes on personal page has been moved to a
separate column.
* Also, now it is possible to specify text of links from descriptions.
The format is [En description http://example.com{Link text}]
> Profile attribute's descriptions improvements

- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/client/PerunSetAffiliationUtils.java
- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/pages/affiliation/AffiliationPresenter.java
- perun-wui-setAffiliation/src/main/java/cz/metacentrum/perun/wui/setAffiliation/pages/affiliation/AffiliationView.java
Updated way how setAffiliation stores time information about affiliation. New way is to store the date when affiliation will expire.
> WUI: updated setAffiliation

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/widgets/ErrorReporter.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/ExceptionResolverImpl.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/model/RegistrarObject.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/VerifyEmailView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/VerifyEmailView.ui.xml
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/FormStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/GroupExtStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/Summary.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryImpl.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java
- perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties
- Added GroupExt step to handle group extension applications.
- Added reading of new form from RegistrarObject.
- Fixed error reporting on empty form.
- Show continue button on mail validation page if "target" param
is present in URL.
> WUI: Support membership extension in a group

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/settings/preferredgroupnames/PreferredGroupNamesView.java
*WUI/profile/settngs/preferredGroupNames
*cancel button in newPreferredNameModal didn't work
> WUI/profile: fixed modal hiding with cancel button

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/JsUtils.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/Utils.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/client/resources/PerunPwdResetTranslation.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
- perun-wui-pwdreset/src/main/resources/cz/metacentrum/perun/wui/pwdreset/client/resources/PerunPwdResetTranslation_cs.properties
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Password.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/EinfraPasswordValidator.java
- perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties
- Check if user has einfra login. If so, check if has reset password
recently (date in specific attribute). If not, offer popup to
go to password reset.
> WUI: Tweak for Metacentrum to force users to re-sign their keys

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalView.java
- When displaying custom name and description on personal page of a
profile app, we used directly localized messages. Now we fallback
on English if current locale has no value - means attribute is set
with single locale name/description.
> WUI: Fallback on english in profile attributes names and descriptions

- perun-wui-profile/src/main/webapp/PerunProfileElixir.html
* Changed logo in profile for elixir to its dark version
* Content of footer is now centered.
> ProfileElixir footer edit

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/identities/IdentitiesPresenter.java
- Once "add new identity" is clicked, we retrieve token and use it
to access identity consolidator.
> WUI: Profile will retrieve token for consolidator

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileView.ui.xml
As the logout in profile view does not work, this hides the logout button from UI.
> Remove sign-out button from profile view

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunTranslation.java
- perun-wui-core/src/main/resources/cz/metacentrum/perun/wui/client/resources/PerunTranslation_cs.properties
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/settings/altPasswords/AltPasswordsView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/settings/samba/SambaPasswordView.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/settings/samba/SambaPasswordView.ui.xml
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/client/resources/PerunPwdResetTranslation.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
- perun-wui-pwdreset/src/main/resources/cz/metacentrum/perun/wui/pwdreset/client/resources/PerunPwdResetTranslation_cs.properties
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemEditable.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Username.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/CheckboxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/ComboboxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/EinfraPasswordValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/EinfraUsernameValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/PasswordValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/PerunFormItemValidatorImpl.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/RadioboxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/SelectionboxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/TextAreaValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/TextFieldValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/TimezoneValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/UsernameValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/ValidatedEmailValidator.java
- perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties
- Added new checks for format and strength of einfra login/password.
- Whenever we work with login or password in "einfra" namespace, then these
checks are preferred and any setting (eg. on form item in registrar) is ignored.
- Added HTML formatted help and error messages, which inform user about
partial problems with entered value.
- Removed any old specific checks for einfra.
> WUI: Introduced UI side login/password check for einfra

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
- If offered "similar user" has only single identity of specific type
(cert/idp/other), show it as a single button, rather than drop-down
with single item.
> WUI: Show single button for similar users identities in registrar

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunErrorTranslation.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/ErrorTranslator.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/PerunException.java
- perun-wui-core/src/main/resources/cz/metacentrum/perun/wui/client/resources/PerunErrorTranslation_cs.properties
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
* Added handling of new exceptions to the pwd-reset app.
* When loading, the application now checks, wheter the link is valid. If
it is expired or invalid, it will not even let the user submit the form.
> PWD Reset - new Exceptions handling

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunTranslation.java
- perun-wui-core/src/main/resources/cz/metacentrum/perun/wui/client/resources/PerunTranslation_cs.properties
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Checkbox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Combobox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/FromFederation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Header.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/HtmlComment.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Password.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItem.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemEditable.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemStatic.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Radiobox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Selectionbox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/SubmitButton.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextArea.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextField.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Timezone.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Undefined.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Username.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/ValidatedEmail.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/EinfraPasswordValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/EinfraUsernameValidator.java
- Check password strength for einfra against users name and login.
We ignore case and diacritics, reverse value is checked too.
Only bits of 3 chars and more are checked to prevent unnecessary
false positive.
- Added check also for password reset app.
> REGISTRAR: Check einfra password strength against form content 

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Attribute.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/columnProviders/AttributeColumnProvider.java
Related to: https://homeproj.cesnet.cz/issues/6883
* removed usage of LargeString and LargeArray as attribute type
> Remove large attributes

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunTranslation.java
- perun-wui-core/src/main/resources/cz/metacentrum/perun/wui/client/resources/PerunTranslation_cs.properties
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
- Password must be at least 12 characters longs.
- Password must consists of at least 3 groups of chars.
> Added password strength check for MU namespace

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/client/PerunPwdResetPresenter.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
- Password reset can now work with parameter "token" in the password reset
link.
- Merge and deploy only after deploying CESNET/perun#3138
> Password reset using token parameter

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/FormStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/GroupExtStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/GroupInitStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/VoExtStep.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/VoInitStep.java
- redirectURL was added to fedInfo of application to be later appended to registration link in validation mail in registrar
> Added redirectURL

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItem.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Checkbox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/GroupCheckBox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItem.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/TextField.java
* Added support for the new form item EMBEDDED_GROUP_APPLICATION
which can be used for automatic group applications.
* When submitting application, user can now select groups to join, after
his vo application has been submitted.
* On submitted application detail, we show only the groups, which user
had selected.
> Registrar - new form item

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunTranslation.java
- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Application.java
- perun-wui-core/src/main/resources/cz/metacentrum/perun/wui/client/resources/PerunTranslation_cs.properties
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/AppDetailView.ui.xml
- perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties
- added support for new application type EMBEDDED
- added info box when viewing embedded applications
> Added new app type embedded

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/client/PerunPwdResetPresenter.java
- perun-wui-pwdreset/src/main/java/cz/metacentrum/perun/wui/pwdreset/pages/PwdResetView.java
- Logic which does not used token for passeord reset was erased from the
code as it is no longer supported on backend
> Removed old logic for password reset

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/resources/PerunConfiguration.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
- added new parameter registrar.hideProxy to perun-web-gui.properties that hides IdPs during VO/Group registrations
- replaced hiding specific IdPs in code by this parameter
> Added hidden proxies parameter to registration

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalPresenter.java
- Validating preferred mail change in user profile is now possible for links with token parameter.
> Profile: preferred mail change using token

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
* customUrl needs to contain link path
* linkPath parameter is used for referer and will be removed
> Use customUrl only in pref. mail change

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/client/utils/JsUtils.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
- expect base64 url safe rather than regular base64 for prefilling the
value
- new methods for encoding/decoding base64urlSafe
- removed confusing call of encoding as base64 in zipString
> Updates for BBMRI inputs

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/managers/UsersManager.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/personal/PersonalPresenter.java
* Removed preferred mail change methods using i/m parameters
> refactor: removed deprecated preferred mail change method

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/ErrorTranslator.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/PerunProfileUtils.java
- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/client/resources/PerunProfileTranslation.java
* error message when adding invalid ssh key has been changed to be more self-explanatory
> fix(profile): fixed wrong error message when adding invalid ssh

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/json/JsonClient.java
* Second request sometimes fails with 403 due to CSRF cookie and user have to refresh window.
> fix(registrar): CSRF authentication bug

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/PerunException.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java
- WUI is expected to ignore soft version of CantBeApprovedException.
Later code processing required Application and its ID to be returned,
but summary contained only Exception thrown and not the Application.
- Now we get application ID from Exception itself.
> fix(registrar): handle CantBeApprovedException

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/ApplicationFormItem.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarResources.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/ListBox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/MapBox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/PerunFormItemEditable.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/WidgetBox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/ListBoxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/MapBoxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/PerunFormItemValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/SshKeysListBoxValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/SshKeysTextAreaValidator.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/validators/SshKeysTextFieldValidator.java
- perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/PerunRegistrarTranslation_cs.properties
- perun-wui-registrar/src/main/resources/cz/metacentrum/perun/wui/registrar/client/resources/css/PerunRegistrar.gss
* Added support for new applicatoin form items.
* Both items have no default input, just add button. With this button, user can add new values to the list or map. Each new value in the list or map has also a remove button, so user can also remove the previously added value.
> feat(registrar): add list and map application form items

- perun-wui-consolidator/src/main/java/cz/metacentrum/perun/wui/consolidator/widgets/Wayf.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/FormView.java
- Explicitly ask IdPs for authnContextClass when generating links
from registrar and consolidator.
> feat: request IdPs to use some AuthnContext class 

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Combobox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Selectionbox.java
- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/items/Timezone.java
* "Not-selected" option added to all types of drop down required items (Selectionbox, Combobox and Timezone).
> feat(registrar): added "not-selected" option to the required selection boxes

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/widgets/PerunFormItemsGeneratorImpl.java
Change name of the form item it tries to prefill.
> fix: 🐛 Fix prefilling collections in BBMRI collections form

- perun-wui-profile/src/main/java/cz/metacentrum/perun/wui/profile/pages/resources/ResourcesPresenter.java
- Do not get member for each resource, as the member is same for all resources from the same VO.
- Temporarily disabled loading of assigned groups. Common users can't call this method, plus loading logic merges all groups together without any mapping to actual resources in the table. This needs to be completely reworked.
> fix: profile resources loading optimization

- perun-wui-registrar/src/main/java/cz/metacentrum/perun/wui/registrar/pages/steps/SummaryStep.java
- After submitting both VO and group app, reload their state to check whether their mails need to be verified. This is needed in case, VO mail needs to be verified and is verified before submitting the group app.
> fix(registrar): check verified mails before submissions

- LICENSE
- README.md
- pom.xml
- Fixed http->https in pom.xml
> docs: fixed year in license and readme

- perun-wui-core/src/main/java/cz/metacentrum/perun/wui/model/beans/Application.java
Added error that caused automatic approval failure of the application.
> feat(core)!: auto-approve error

- .releaserc.json
> Revert "ci: use conventional commits preset for release"

- .commitlintrc.json
- .github/workflows/check.yml
- .github/workflows/semantic-release.yml
- .gitignore
- .releaserc.json
- README.md
- package-lock.json
- package.json
* added check.yml workflow
* added .commitlintrc.json with specific rules
* changed README.md for consistency
> ci: upgrade notes

- .github/workflows/semantic-release.yml
upgrade node version to lts in semantic-release.yml
> fixup! ci: upgrade notes

- .github/workflows/semantic-release.yml
add distribution to setup-java action
> fixup! chore: upgrade versions of actions in semantic-release.yml
